networks:
  sclad_net:
    name: sclad_net
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:14.17-alpine3.21
    environment:
      POSTGRES_DB: "django-app-db"
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "89U1JKpkBQVTErtpIgfi"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/psql/data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 700M
        reservations:
          memory: 700M
    restart: unless-stopped
    networks:
      sclad_net:
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://0.0.0.0:12201  #"udp://10.10.15.118:12201"  #udp://0.0.0.0:12201 #localhost:24224
        tag: postgress

  django-app:
    container_name: my_docker_blog
    image: sclad3test-django-app
    # build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=django-app-db
      - DB_USER=app_user
      - DB_PASSWORD=89U1JKpkBQVTErtpIgfi
    volumes:
      - ./:/app/
      - image-store:/etc/data/images
    networks:
      sclad_net:

volumes:
  image-store:
