name: project sclad3 CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/test-ci'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: 5.44.44.188
          remote: /opt/sclad3test
          port: 22
          user: github
          key: ${{ secrets.SSH_KEY }}
        
  launch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the code.
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 5.44.44.188
          username: github
          key: ${{ secrets.SSH_KEY }}
          # port: 22
          script: |
            cd /opt/sclad3test
            docker-compose down
            docker-compose up -d


