name: project sclad3 CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/test-ci'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      # Checkout the code.
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 5.44.44.188
          username: github
          key: ${{ secrets.SSH_KEY }}
          # port: 22
          script: whoami